import test from 'node:test';
import assert from 'node:assert/strict';
import { createNotebookRepository, validateNotebook, chatNotebooks } from '../server/notebooks.mjs';
import { createHandler } from '../netlify/functions/ask.mjs';
function memory(seed={entries:[]}){let data=seed,etag=seed?'v0':'',version=0;return {async getWithMetadata(){return data?{data:structuredClone(data),etag}:null;},async setJSON(key,next,options){if((options.onlyIfNew && data) || (options.onlyIfMatch && options.onlyIfMatch!==etag))return {modified:false};data=structuredClone(next);etag='v'+(++version);return {modified:true,etag};}};}
const admin={email:'admin@school.test',admin:true,name:'Admin'},staff={email:'staff@school.test',admin:false,name:'Staff'};
const row={department:'Music',title:'Music staff notebook',description:'Music procedures',owner:'Music team',notebookUrl:'https://notebooklm.google.com/notebook/music-one',approved:true,enabled:true};
const env={GOOGLE_CLIENT_ID:'client',GOOGLE_ALLOWED_DOMAIN:'school.test',ADMIN_EMAILS:admin.email,STAFF_EMAILS:staff.email,NOTEBOOKLM_CHAT_ENDPOINT:'https://gateway.school.test/chat',NOTEBOOKLM_GATEWAY_TOKEN:'secret'};
const request=(route,method='GET',body)=>new Request('https://ask.test/.netlify/functions/ask?route='+route,{method,...(body?{body:JSON.stringify(body)}:{})});
test('LS CCA reference stays inactive until approval and survives archiving',async()=>{const repo=createNotebookRepository(()=>store),store=memory(null);let catalog=await repo.read();assert.equal(catalog.entries[0].department,'Lower School CCA');assert.equal(validateNotebook(catalog.entries[0]).notebookId,'2c5a8878-77fc-4d45-90a0-7cb1444f1d14');assert.equal(catalog.entries[0].approved,false);assert.equal(chatNotebooks(catalog).length,0);catalog=await repo.write({action:'save',id:'demo-ls-cca',notebook:{...catalog.entries[0],owner:'LS team'}},catalog.revision,admin);assert.equal(catalog.entries.length,1);catalog=await repo.write({action:'archive',id:'demo-ls-cca'},catalog.revision,admin);assert.equal((await repo.read()).entries[0].archived,true);});
test('department draft can be saved before its notebook exists',async()=>{const draft=validateNotebook({...row,notebookUrl:'',enabled:false,approved:false});assert.equal(draft.notebookId,'');assert.equal(draft.enabled,false);});
test('notebook links resolve IDs and reject deceptive URLs or mismatches',()=>{assert.equal(validateNotebook(row).notebookId,'music-one');for(const notebookUrl of ['http://notebooklm.google.com/notebook/one','https://notebooklm.google.com.evil.test/notebook/one','https://user:pass@notebooklm.google.com/notebook/one','https://notebooklm.google.com/notebook/one?token=secret'])assert.throws(()=>validateNotebook({...row,notebookUrl}));assert.throws(()=>validateNotebook({...row,notebookId:'other'}));});
test('enable requires a real reference and all-staff approval',()=>{assert.throws(()=>validateNotebook({...row,approved:false}));assert.throws(()=>validateNotebook({...row,notebookUrl:'',notebookId:''}));});
test('registry persists changes, rejects stale saves and duplicate notebooks',async()=>{const store=memory(),repo=createNotebookRepository(()=>store);let catalog=await repo.write({action:'save',notebook:row},'v0',admin);assert.equal((await repo.read()).entries.length,1);await assert.rejects(repo.write({action:'save',notebook:{...row,department:'Other'}},catalog.revision,admin),/DUPLICATE_NOTEBOOK/);await assert.rejects(repo.write({action:'save',id:catalog.entries[0].id,notebook:row},'v0',admin),/CATALOG_CHANGED/);catalog=await repo.write({action:'save',id:catalog.entries[0].id,notebook:{...row,owner:'Updated team'}},catalog.revision,admin);assert.equal((await repo.read()).entries[0].owner,'Updated team');});
test('archiving immediately removes a notebook from chat and it can be restored',async()=>{const store=memory(),repo=createNotebookRepository(()=>store);let catalog=await repo.write({action:'save',notebook:row},'v0',admin);const id=catalog.entries[0].id;catalog=await repo.write({action:'archive',id},catalog.revision,admin);assert.equal(chatNotebooks(catalog,{NOTEBOOKLM_NOTEBOOK_ID:'legacy'}).length,0);catalog=await repo.write({action:'save',id,notebook:row},catalog.revision,admin);assert.equal(chatNotebooks(catalog).length,1);assert.equal(catalog.entries[0].archived,false);});
test('staff cannot inspect or mutate department notebook registry',async()=>{const repo=createNotebookRepository(()=>memory());const h=createHandler(env,fetch,async()=>staff,repo);for(const method of ['GET','POST'])assert.equal((await h(request('notebooks',method,method==='POST'?{action:'save',revision:'',notebook:row}:null))).status,403);});
test('admins can save departments without a chat gateway configured',async()=>{const store=memory(null),repo=createNotebookRepository(()=>store);const h=createHandler({...env,NOTEBOOKLM_GATEWAY_TOKEN:''},fetch,async()=>admin,repo);assert.equal((await h(request('notebooks','POST',{action:'save',revision:'',notebook:{...row,enabled:false}}))).status,200);const config=await(await h(request('config'))).json();assert.equal(config.authReady,true);assert.equal(config.ready,false);assert.equal((await h(request('chat','POST',{message:'Hello'}))).status,503);});
test('chat sends only approved enabled notebooks and ignores browser source overrides',async()=>{const entries=[{...validateNotebook(row),id:'music'},{...validateNotebook({...row,department:'Sports',notebookUrl:'https://notebooklm.google.com/notebook/sports-one'}),id:'sports'},{...validateNotebook({...row,department:'Draft',notebookUrl:'',enabled:false}),id:'draft'},{...validateNotebook({...row,notebookUrl:'https://notebooklm.google.com/notebook/paused',enabled:false}),id:'paused'}];let sent;const h=createHandler(env,async(url,options)=>{sent=JSON.parse(options.body);return Response.json({provider:'notebooklm',supported:true,text:'A supported cross-department answer.',citations:[{title:'Music source',sourceId:'music-source',notebookId:'music-one'},{title:'Sports source',sourceId:'sports-source',notebookId:'sports-one'}]});},async()=>staff,{read:async()=>({entries})});const data=await(await h(request('chat','POST',{message:'How?',notebooks:[{notebookId:'evil'}]}))).json();assert.deepEqual(sent.notebooks.map(n=>n.notebookId),['music-one','sports-one']);assert.equal(data.supported,true);assert.deepEqual(data.citations.map(c=>c.department),['Music','Sports']);});
test('citations from excluded notebooks withhold the entire answer',async()=>{const h=createHandler(env,async()=>Response.json({provider:'notebooklm',supported:true,text:'Private answer',citations:[{title:'Wrong source',sourceId:'one',notebookId:'private-notebook'}]}),async()=>staff,{read:async()=>({entries:[{...validateNotebook(row),id:'music'}]})});const data=await(await h(request('chat','POST',{message:'How?'}))).json();assert.equal(data.supported,false);assert(!data.text.includes('Private answer'));});
test('an empty registry never produces a request to the gateway',async()=>{let called=false;const h=createHandler(env,async()=>{called=true;},async()=>staff,{read:async()=>({entries:[]})});assert.equal((await h(request('chat','POST',{message:'How?'}))).status,503);assert.equal(called,false);});

test('provided Google notebook URL is accepted while deceptive hostnames are rejected',()=>{const url='https://notebook.google.com/notebook/2c5a8878-77fc-4d45-90a0-7cb1444f1d14';assert.equal(validateNotebook({...row,notebookUrl:url}).notebookId,'2c5a8878-77fc-4d45-90a0-7cb1444f1d14');assert.throws(()=>validateNotebook({...row,notebookUrl:url.replace('notebook.google.com','notebook.google.com.evil.test')}));});
