import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');
const source=await readFile(new URL('../public/notebooks.js',import.meta.url),'utf8');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function screen({admin=false,authReady=false,entries=[],failSave=false}={}){
  const dom=new JSDOM(html,{url:'https://harrow.test/',runScripts:'outside-only'}),w=dom.window,d=w.document;
  let user=admin?{email:'admin@school.test',admin:true}:null,catalog={entries,revision:'one',gatewayReady:false};const calls=[];
  w.confirm=()=>true;
  const api=async(route,body)=>{calls.push({route,body});if(body){if(failSave)throw new Error('CATALOG_CHANGED');if(body.action==='archive')catalog.entries=catalog.entries.map(e=>e.id===body.id?{...e,archived:true,enabled:false}:e);else catalog.entries=[...catalog.entries,{...body.notebook,id:'saved-id'}];catalog.revision='two';}return structuredClone(catalog);};
  const setup=w.Function(source.replace('export function','function')+';return setupNotebooks;')();
  const registry=setup({api,getUser:()=>user,getConfig:()=>({authReady}),onChange:async()=>{}});
  return {w,d,calls,registry,setUser(value){user=value;},click(id){d.getElementById(id).click();}};
}
test('department screen is reviewable before sign-in and cannot save anonymously',async()=>{const s=screen();s.click('notebooks');await tick();assert.equal(s.d.getElementById('notebook-panel').hidden,false);assert.equal(s.d.getElementById('staff-chat').hidden,true);assert.equal(s.d.getElementById('notebook-fields').disabled,true);assert.equal(s.calls.length,0);assert.match(s.d.getElementById('registry-access').textContent,/not configured/);s.click('back-chat');assert.equal(s.d.getElementById('staff-chat').hidden,false);s.w.close();});
test('admin can save a draft department and sees it in the registry',async()=>{const s=screen({admin:true,authReady:true});s.click('notebooks');await tick();const f=s.d.getElementById('notebook-form');f.elements.department.value='Music';f.elements.title.value='Music staff notebook';f.elements.description.value='Music questions';f.dispatchEvent(new s.w.Event('submit',{bubbles:true,cancelable:true}));await tick();const call=s.calls.find(c=>c.body);assert.equal(call.body.revision,'one');assert.equal(call.body.notebook.department,'Music');assert.equal(call.body.notebook.enabled,false);assert.equal(s.d.getElementById('department-count').textContent,'1');assert.match(s.d.getElementById('notebook-list').textContent,/Notebook needed/);assert.match(s.d.getElementById('registry-status').textContent,/connection is still pending/);s.w.close();});
test('form includes notebook and approval fields in the saved record',async()=>{const s=screen({admin:true,authReady:true});s.click('notebooks');await tick();const f=s.d.getElementById('notebook-form');f.elements.department.value='Sports';f.elements.title.value='Sports notebook';f.elements.notebookUrl.value='https://notebooklm.google.com/notebook/sport';f.elements.approved.checked=true;f.elements.enabled.checked=true;f.dispatchEvent(new s.w.Event('submit',{cancelable:true}));await tick();const saved=s.calls.find(c=>c.body).body.notebook;assert.equal(saved.enabled,true);assert.equal(saved.approved,true);assert.match(saved.notebookUrl,/notebook\/sport/);s.w.close();});
test('archive updates the list and archived entries can be found for restoration',async()=>{const s=screen({admin:true,authReady:true,entries:[{id:'music',department:'Music',title:'Music notebook',description:'Music questions',enabled:true,approved:true,notebookId:'one',notebookUrl:'',archived:false}]});s.click('notebooks');await tick();[...s.d.querySelectorAll('#notebook-list button')].find(b=>b.textContent==='Archive').click();await tick();assert.equal(s.calls.find(c=>c.body).body.action,'archive');assert.equal(s.d.getElementById('department-count').textContent,'0');s.click('show-archived');assert.match(s.d.getElementById('notebook-list').textContent,/Restore \/ edit/);s.w.close();});
test('conflicting edits are surfaced and private records clear on sign-out',async()=>{const s=screen({admin:true,authReady:true,failSave:true,entries:[{id:'music',department:'Music',title:'Notebook',description:'<img src=x onerror=alert(1)>',archived:false}]});s.click('notebooks');await tick();assert.equal(s.d.querySelectorAll('#notebook-list img').length,0);const f=s.d.getElementById('notebook-form');f.elements.department.value='Other';f.elements.title.value='Other notebook';f.dispatchEvent(new s.w.Event('submit',{cancelable:true}));await tick();assert.match(s.d.getElementById('registry-status').textContent,/Another administrator/);s.setUser(null);s.registry.sync();assert.equal(s.d.getElementById('department-count').textContent,'0');assert.equal(s.d.getElementById('notebook-fields').disabled,true);s.w.close();});
