import {initialDepartments} from '../public/notebook-drafts.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');
const source=await readFile(new URL('../public/notebooks.js',import.meta.url),'utf8');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function screen({admin=false,authReady=false,entries=[],failSave=false,userEmail='',manageSources=false,gatewayReady=false,provider='notebooklm'}={}){
  const dom=new JSDOM(html,{url:'https://harrow.test/',runScripts:'outside-only'}),w=dom.window,d=w.document;
  let user=admin?{email:'admin@school.test',admin:true}:userEmail?{email:userEmail,admin:false,manageSources}:null,catalog={entries,revision:'one',gatewayReady,provider};const calls=[];
  w.confirm=()=>true;
  const api=async(route,body)=>{calls.push({route,body});if(route==='sync')return {status:body.action==='start'?'Synced':'Never synced',lastSuccessfulSync:body.action==='start'?'2026-10-05T10:00:00Z':null,sourceCount:body.action==='start'?1:0,files:body.action==='start'?[{id:'one',name:'CCA guidance',version:'2',modifiedTime:'2026-10-05'}]:[]};if(body){if(failSave)throw new Error('CATALOG_CHANGED');if(body.action==='archive')catalog.entries=catalog.entries.map(e=>e.id===body.id?{...e,archived:true,enabled:false}:e);else catalog.entries=[...catalog.entries,{...body.notebook,id:'saved-id'}];catalog.revision='two';}return structuredClone(catalog);};
  const setup=w.Function('initialDepartments',source.replace(/^import[^\n]+\n/,'').replace('export function','function')+';return setupNotebooks;')(initialDepartments);
  const registry=setup({api,getUser:()=>user,getConfig:()=>({authReady}),onChange:async()=>{}});
  return {w,d,calls,registry,setUser(value){user=value;},click(id){d.getElementById(id).click();}};
}
test('department screen is reviewable before sign-in and cannot save anonymously',async()=>{const s=screen();s.click('notebooks');await tick();assert.equal(s.d.getElementById('notebook-panel').hidden,false);assert.equal(s.d.getElementById('staff-chat').hidden,true);assert.equal(s.d.getElementById('notebook-fields').disabled,true);assert.equal(s.calls.length,0);assert.match(s.d.getElementById('notebook-list').textContent,/Lower School CCA/);assert.match(s.d.getElementById('notebook-list').textContent,/Review pending/);assert.equal(s.d.querySelector('#notebook-list a').href,'https://notebook.google.com/notebook/2c5a8878-77fc-4d45-90a0-7cb1444f1d14');assert.match(s.d.getElementById('registry-access').textContent,/not configured/);s.click('back-chat');assert.equal(s.d.getElementById('staff-chat').hidden,false);s.w.close();});
test('admin can save a draft department and sees it in the registry',async()=>{const s=screen({admin:true,authReady:true});s.click('notebooks');await tick();const f=s.d.getElementById('notebook-form');f.elements.department.value='Music';f.elements.title.value='Music staff notebook';f.elements.description.value='Music questions';f.dispatchEvent(new s.w.Event('submit',{bubbles:true,cancelable:true}));await tick();const call=s.calls.find(c=>c.body);assert.equal(call.body.revision,'one');assert.equal(call.body.notebook.department,'Music');assert.equal(call.body.notebook.enabled,false);assert.equal(s.d.getElementById('department-count').textContent,'1');assert.match(s.d.getElementById('notebook-list').textContent,/Notebook needed/);assert.match(s.d.getElementById('registry-status').textContent,/connection is still pending/);s.w.close();});
test('form includes notebook and approval fields in the saved record',async()=>{const s=screen({admin:true,authReady:true});s.click('notebooks');await tick();const f=s.d.getElementById('notebook-form');f.elements.department.value='Sports';f.elements.title.value='Sports notebook';f.elements.notebookUrl.value='https://notebooklm.google.com/notebook/sport';f.elements.approved.checked=true;f.elements.enabled.checked=true;f.dispatchEvent(new s.w.Event('submit',{cancelable:true}));await tick();const saved=s.calls.find(c=>c.body).body.notebook;assert.equal(saved.enabled,true);assert.equal(saved.approved,true);assert.match(saved.notebookUrl,/notebook\/sport/);s.w.close();});
test('archive updates the list and archived entries can be found for restoration',async()=>{const s=screen({admin:true,authReady:true,entries:[{id:'music',department:'Music',title:'Music notebook',description:'Music questions',enabled:true,approved:true,notebookId:'one',notebookUrl:'',archived:false}]});s.click('notebooks');await tick();[...s.d.querySelectorAll('#notebook-list button')].find(b=>b.textContent==='Archive').click();await tick();assert.equal(s.calls.find(c=>c.body).body.action,'archive');assert.equal(s.d.getElementById('department-count').textContent,'0');s.click('show-archived');assert.match(s.d.getElementById('notebook-list').textContent,/Restore \/ edit/);s.w.close();});
test('conflicting edits are surfaced and private records clear on sign-out',async()=>{const s=screen({admin:true,authReady:true,failSave:true,entries:[{id:'music',department:'Music',title:'Notebook',description:'<img src=x onerror=alert(1)>',archived:false}]});s.click('notebooks');await tick();assert.equal(s.d.querySelectorAll('#notebook-list img').length,0);const f=s.d.getElementById('notebook-form');f.elements.department.value='Other';f.elements.title.value='Other notebook';f.dispatchEvent(new s.w.Event('submit',{cancelable:true}));await tick();assert.match(s.d.getElementById('registry-status').textContent,/Another administrator/);s.setUser(null);s.registry.sync();assert.equal(s.d.getElementById('department-count').textContent,'1');assert(!s.d.getElementById('notebook-list').textContent.includes('Music'));assert.equal(s.d.getElementById('notebook-fields').disabled,true);s.w.close();});

test('department lead can sync their own sources while administrative edits stay disabled',async()=>{const entry={id:'cca',department:'LS CCA',title:'CCA',description:'Guidance',ownerEmail:'lead@school.test',driveFolderId:'folder',approved:true,enabled:true};const s=screen({authReady:true,userEmail:'lead@school.test',manageSources:true,gatewayReady:true,provider:'drive-file-search',entries:[entry]});s.click('notebooks');await tick();assert.equal(s.d.getElementById('notebook-fields').disabled,true);const button=[...s.d.querySelectorAll('#notebook-list button')].find(b=>b.textContent==='Sync department');assert.equal(button.disabled,false);button.click();await tick();assert.match(s.d.getElementById('registry-status').textContent,/Sync complete/);assert.match(s.d.getElementById('notebook-list').textContent,/CCA guidance/);assert.equal(s.d.getElementById('enabled-count').textContent,'1');s.setUser(null);s.registry.sync();assert(!s.d.getElementById('notebook-list').textContent.includes('CCA guidance'));s.w.close();});
test('another department and unconfigured source services cannot be synced from the interface',async()=>{for(const [owner,gatewayReady] of [['other@school.test',true],['lead@school.test',false]]){const s=screen({authReady:true,userEmail:'lead@school.test',manageSources:true,gatewayReady,provider:'drive-file-search',entries:[{id:'cca',department:'LS CCA',title:'CCA',description:'Guidance',ownerEmail:owner,driveFolderId:'folder',approved:true,enabled:true}]});s.click('notebooks');await tick();const button=[...s.d.querySelectorAll('#notebook-list button')].find(b=>b.textContent==='Sync department');assert.equal(button.disabled,true);s.w.close();}});
