import test from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,sign} from 'node:crypto';
import {createHandler} from '../netlify/functions/ask.mjs';
const {publicKey,privateKey}=generateKeyPairSync('rsa',{modulusLength:2048});
const jwk={...publicKey.export({format:'jwk'}),kid:'test-key',alg:'RS256'};
const env={GOOGLE_CLIENT_ID:'school-client',GOOGLE_ALLOWED_DOMAIN:'school.test',ADMIN_EMAILS:'admin@school.test',STAFF_EMAILS:'staff@school.test',GEMINI_API_KEY:'server-secret',GEMINI_FILE_SEARCH_STORE:'fileSearchStores/school',GEMINI_MODEL:'configured-model'};
function jwt(overrides={}){const h=Buffer.from(JSON.stringify({alg:'RS256',kid:'test-key'})).toString('base64url'),p=Buffer.from(JSON.stringify({iss:'https://accounts.google.com',aud:env.GOOGLE_CLIENT_ID,exp:Date.now()/1000+3600,iat:Date.now()/1000,sub:'123',email_verified:true,hd:'school.test',email:'staff@school.test',...overrides})).toString('base64url');return h+'.'+p+'.'+sign('RSA-SHA256',Buffer.from(h+'.'+p),privateKey).toString('base64url');}
function request(route,{token=jwt(),method='GET',body,origin}={}){return new Request('https://ask.test/.netlify/functions/ask?route='+route,{method,headers:{...(token?{authorization:'Bearer '+token}:{}),...(origin?{origin}:{}),'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});}
let calls=[];let model={};
const fetcher=async(url,options)=>{calls.push({url,options});if(url.includes('oauth2'))return Response.json({keys:[jwk]});if(url.includes(':generateContent'))return Response.json(model);return Response.json({documents:[]});};
const handler=createHandler(env,fetcher);
test('public config excludes secrets and source location',async()=>{const body=await (await handler(request('config',{token:''}))).text();assert(!body.includes('server-secret'));assert(!body.includes('fileSearchStores'));assert(!body.includes('admin@'));});
test('rejects no token, tampering, wrong audience, expiry and unverified email',async()=>{for(const token of ['',jwt().slice(0,-8)+'badtoken',jwt({aud:'other'}),jwt({exp:1}),jwt({email_verified:false}),jwt({hd:'other.test'})])assert.equal((await handler(request('session',{token}))).status,401);});
test('domain account alone does not authorise pupil or unknown staff',async()=>{assert.equal((await handler(request('session',{token:jwt({email:'pupil@school.test'})}))).status,403);});
test('staff cannot list, upload, delete or inspect operations',async()=>{for(const [route,method] of [['documents','GET'],['upload','POST'],['documents','DELETE'],['operation','GET']])assert.equal((await handler(request(route,{method}))).status,403);});
test('admin can list sources but cannot delete outside configured store',async()=>{const token=jwt({email:'admin@school.test'});assert.equal((await handler(request('documents',{token}))).status,200);assert.equal((await handler(request('documents&name=fileSearchStores/other/documents/one',{token,method:'DELETE'}))).status,400);});
test('cross-origin requests rejected',async()=>{assert.equal((await handler(request('chat',{origin:'https://evil.test',method:'POST',body:{message:'Hello'}}))).status,403);});
test('unsupported generated answers are withheld',async()=>{model={candidates:[{finishReason:'STOP',content:{parts:[{text:'Invented policy'}]}}]};const data=await(await handler(request('chat',{method:'POST',body:{message:'What is the policy?'}}))).json();assert.equal(data.supported,false);assert(!data.text.includes('Invented'));});
test('grounded answer returned; client cannot choose store or reveal API key',async()=>{model={candidates:[{finishReason:'STOP',content:{parts:[{text:'Submit the form.'}]},groundingMetadata:{groundingChunks:[{retrievedContext:{title:'Staff handbook',uri:'private-source'}}],groundingSupports:[{groundingChunkIndices:[0]}]}}]};const data=await(await handler(request('chat',{method:'POST',body:{message:'How?',store:'evil',language:'th'}}))).json();assert.equal(data.text,'Submit the form.');assert.deepEqual(data.citations,[{title:'Staff handbook'}]);const sent=JSON.parse(calls.at(-1).options.body);assert.deepEqual(sent.tools[0].fileSearch.fileSearchStoreNames,[env.GEMINI_FILE_SEARCH_STORE]);assert(sent.systemInstruction.parts[0].text.includes('Thai'));});
test('invalid and oversized questions rejected',async()=>{for(const message of ['',null,'x'.repeat(2001)])assert.equal((await handler(request('chat',{method:'POST',body:{message}}))).status,400);});
test('unconfigured service fails closed',async()=>{const unconfigured=createHandler({},fetcher);assert.equal((await unconfigured(request('chat',{method:'POST',body:{message:'Hello'}}))).status,503);});
test('admin upload requires approval and stores audience metadata on Google only',async()=>{let metadata;const uploadFetch=async(url,options)=>{if(url.includes('oauth2'))return Response.json({keys:[jwk]});if(options.headers['X-Goog-Upload-Command']==='start'){metadata=JSON.parse(options.body);return new Response('',{headers:{'x-goog-upload-url':'https://generativelanguage.googleapis.com/upload/session'}});}return Response.json({name:'fileSearchStores/school/upload/operations/one'});};const uploadHandler=createHandler(env,uploadFetch);function upload(approved){const form=new FormData();form.set('title','School handbook');form.set('department','Operations');form.set('file',new Blob(['School test document'],{type:'text/plain'}),'handbook.txt');if(approved)form.set('approved','true');return new Request('https://ask.test/.netlify/functions/ask?route=upload',{method:'POST',headers:{authorization:'Bearer '+jwt({email:'admin@school.test'})},body:form});}assert.equal((await uploadHandler(upload(false))).status,400);assert.equal((await uploadHandler(upload(true))).status,200);assert(metadata.customMetadata.some(m=>m.key==='audience'&&m.stringValue==='staff'));assert(metadata.customMetadata.some(m=>m.key==='approvedBy'&&m.stringValue==='admin@school.test'));});
