import test from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,sign} from 'node:crypto';
import {createHandler as createRealHandler} from '../netlify/functions/ask.mjs';
const createHandler=(env,fetcher)=>createRealHandler(env,fetcher,undefined,{read:async()=>({entries:[]})});
const {publicKey,privateKey}=generateKeyPairSync('rsa',{modulusLength:2048});
const jwk={...publicKey.export({format:'jwk'}),kid:'test-key',alg:'RS256'};
const env={GOOGLE_CLIENT_ID:'school-client',GOOGLE_ALLOWED_DOMAIN:'school.test',ADMIN_EMAILS:'admin@school.test',STAFF_EMAILS:'staff@school.test',NOTEBOOKLM_GATEWAY_TOKEN:'server-secret',NOTEBOOKLM_CHAT_ENDPOINT:'https://notebook-gateway.school.test/chat',NOTEBOOKLM_NOTEBOOK_ID:'school-notebook'};
function jwt(overrides={}){const h=Buffer.from(JSON.stringify({alg:'RS256',kid:'test-key'})).toString('base64url'),p=Buffer.from(JSON.stringify({iss:'https://accounts.google.com',aud:env.GOOGLE_CLIENT_ID,exp:Date.now()/1000+3600,iat:Date.now()/1000,sub:'123',email_verified:true,hd:'school.test',email:'staff@school.test',...overrides})).toString('base64url');return h+'.'+p+'.'+sign('RSA-SHA256',Buffer.from(h+'.'+p),privateKey).toString('base64url');}
function request(route,{token=jwt(),method='GET',body,origin}={}){return new Request('https://ask.test/.netlify/functions/ask?route='+route,{method,headers:{...(token?{authorization:'Bearer '+token}:{}),...(origin?{origin}:{}),'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});}
let calls=[];let model={};
const fetcher=async(url,options)=>{calls.push({url,options});if(url.includes('oauth2'))return Response.json({keys:[jwk]});if(url.includes('notebook-gateway'))return Response.json(model);return Response.json({documents:[]});};
const handler=createHandler(env,fetcher);
test('public config excludes secrets and source location',async()=>{const body=await (await handler(request('config',{token:''}))).text();assert(!body.includes('server-secret'));assert(!body.includes('notebook-gateway'));assert(!body.includes('admin@'));});
test('rejects no token, tampering, wrong audience, expiry and unverified email',async()=>{for(const token of ['',jwt().slice(0,-8)+'badtoken',jwt({aud:'other'}),jwt({exp:1}),jwt({email_verified:false}),jwt({hd:'other.test'})])assert.equal((await handler(request('session',{token}))).status,401);});
test('domain account alone does not authorise pupil or unknown staff',async()=>{assert.equal((await handler(request('session',{token:jwt({email:'pupil@school.test'})}))).status,403);});

test('cross-origin request rejected',async()=>{assert.equal((await handler(request('chat',{origin:'https://evil.test',method:'POST',body:{message:'Hello'}}))).status,403);});
test('legacy document and upload endpoints are unavailable',async()=>{for(const route of ['documents','upload','operation'])assert.equal((await handler(request(route,{method:'POST',body:{message:'Hello'}}))).status,404);});
test('unconfigured NotebookLM fails closed even when old Gemini variables exist',async()=>{const h=createHandler({GEMINI_API_KEY:'old-key',GEMINI_FILE_SEARCH_STORE:'fileSearchStores/old'},fetcher);assert.equal((await h(request('chat',{method:'POST',body:{message:'Hello'}}))).status,503);assert.equal((await(await h(request('config'))).json()).ready,false);});
test('non NotebookLM, wrong notebook, or missing citations withheld',async()=>{for(const data of [{text:'Invented policy'},{provider:'gemini',notebookId:'school-notebook',supported:true,text:'Wrong source',citations:[{title:'Handbook',sourceId:'one'}]},{provider:'notebooklm',notebookId:'other',supported:true,text:'Wrong notebook',citations:[{title:'Handbook',sourceId:'one'}]},{provider:'notebooklm',notebookId:'school-notebook',supported:true,text:'No evidence',citations:[]}]){model=data;const answer=await(await handler(request('chat',{method:'POST',body:{message:'How?'}}))).json();assert.equal(answer.supported,false);assert.equal(answer.citations.length,0);}});
test('supported NotebookLM answer stays in chat with source titles',async()=>{model={provider:'notebooklm',notebookId:'school-notebook',supported:true,text:'Use the approved form.',citations:[{title:'Staff handbook',sourceId:'one',url:'private-source'}]};const data=await(await handler(request('chat',{method:'POST',body:{message:'How?',language:'th',notebookId:'evil',provider:'gemini'}}))).json();assert.equal(data.text,'Use the approved form.');assert.deepEqual(data.citations,[{title:'Staff handbook',sourceId:'one',notebookId:'school-notebook',department:'School knowledge'}]);const call=calls.at(-1);assert.equal(call.url,env.NOTEBOOKLM_CHAT_ENDPOINT);const sent=JSON.parse(call.options.body);assert.equal(sent.notebookId,'school-notebook');assert.equal(sent.sourcePolicy,'notebook-only');assert.equal(sent.language,'th');assert.equal(call.options.redirect,'error');});
test('invalid and oversized questions rejected',async()=>{for(const message of ['',null,'x'.repeat(2001)])assert.equal((await handler(request('chat',{method:'POST',body:{message}}))).status,400);});
test('gateway errors do not expose credentials',async()=>{const h=createHandler(env,async(url)=>{if(url.includes('oauth2'))return Response.json({keys:[jwk]});throw new Error('server-secret');});const res=await h(request('chat',{method:'POST',body:{message:'Hello'}}));assert.equal(res.status,502);assert(!(await res.text()).includes('server-secret'));});
test('unsafe gateway config does not become ready',async()=>{for(const endpoint of ['http://school.test','https://localhost/chat','https://user:password@school.test/chat','https://127.0.0.1/chat']){const h=createHandler({...env,NOTEBOOKLM_CHAT_ENDPOINT:endpoint},fetcher);assert.equal((await(await h(request('config'))).json()).ready,false);}});
