import test from 'node:test';
import assert from 'node:assert/strict';
import { createSourceSync } from '../server/source-sync.mjs';
import { driveSearchReady, groundedDriveAnswer, validateSourceFiles } from '../server/drive-search.mjs';
import { validateNotebook } from '../server/notebooks.mjs';
import { createHandler } from '../netlify/functions/ask.mjs';
const lead={email:'lead@school.test',admin:false},other={email:'other@school.test',admin:false},admin={email:'admin@school.test',admin:true};
const entry={id:'cca',department:'LS CCA',driveFolderId:'folder-one',ownerEmail:lead.email,enabled:true,approved:true,archived:false};
const file={id:'file-one',name:'CCA guidance.pdf',mimeType:'application/pdf',modifiedTime:'2026-10-05T09:00:00Z',version:'1'};
function memory(){const rows=new Map();let v=0;return {async getWithMetadata(key){return structuredClone(rows.get(key)||null);},async setJSON(key,data,options){const old=rows.get(key);if((options.onlyIfNew && old)||(options.onlyIfMatch && options.onlyIfMatch!==old?.etag))return {modified:false};const etag=String(++v);rows.set(key,{data:structuredClone(data),etag});return {modified:true,etag};}};}
function fixture(){let files=[file],failure=false,pending=false;const calls=[];let count=0;const provider={async list(folder){calls.push(['list',folder]);return structuredClone(files);},async create(){return 'fileSearchStores/store-'+(++count);},async upload(){if(failure)throw Error('secret-key');return pending?{name:'operations/one',done:false}:{done:true};},async operation(){return {done:true};}};const sync=createSourceSync(provider,()=>memoryStore),memoryStore=memory();return {sync,calls,setFiles(v){files=v;},fail(){failure=true;},pending(){pending=true;}};}
async function finish(f,e=entry){let status=await f.sync.start(lead,e);for(let i=0;i<10 && status.status==='Syncing';i++)status=await f.sync.step(lead,e,status.jobId);return status;}
test('manual sync publishes a complete versioned set and replaces removed documents',async()=>{const f=fixture();f.setFiles([file,{...file,id:'second',name:'Cover.pdf'}]);const initial=await finish(f);assert.equal(initial.status,'Synced');assert.equal(initial.sourceCount,2);f.setFiles([{...file,version:'2',modifiedTime:'2026-10-05T10:00:00Z'}]);const job=await f.sync.start(lead,entry);assert.equal((await f.sync.active([entry]))[0].files.length,2);await f.sync.step(lead,entry,job.jobId);await f.sync.step(lead,entry,job.jobId);const final=await f.sync.step(lead,entry,job.jobId);assert.equal(final.sourceCount,1);assert.equal(final.files[0].version,'2');assert.equal((await f.sync.active([entry]))[0].store,'fileSearchStores/store-2');});
test('failed import retains the last good set and shows a sanitised error',async()=>{const f=fixture();await finish(f);f.fail();const status=await finish(f);assert.equal(status.status,'Failed');assert.equal(status.error,'SOURCE_SERVICE_UNAVAILABLE');assert.equal((await f.sync.active([entry]))[0].store,'fileSearchStores/store-1');assert(!JSON.stringify(status).includes('secret-key'));});
test('folder edits during a sync cannot publish a mixed snapshot',async()=>{const f=fixture();const job=await f.sync.start(lead,entry);await f.sync.step(lead,entry,job.jobId);await f.sync.step(lead,entry,job.jobId);f.setFiles([{...file,version:'changed'}]);const status=await f.sync.step(lead,entry,job.jobId);assert.equal(status.status,'Failed');assert.equal(status.error,'SOURCE_CHANGED');assert.equal((await f.sync.active([entry])).length,0);});
test('department lead is confined to assigned sources and approval is required',async()=>{const f=fixture();await assert.rejects(f.sync.start(other,entry),/DEPARTMENT_ACCESS_REQUIRED/);await assert.rejects(f.sync.status(other,entry),/DEPARTMENT_ACCESS_REQUIRED/);await assert.rejects(f.sync.start(lead,{...entry,approved:false}),/SOURCE_APPROVAL_REQUIRED/);const status=await f.sync.start(admin,entry);assert.equal(status.status,'Syncing');assert.equal(f.calls.length,0);});
test('asynchronous indexing is polled before publication and interrupted sync can resume',async()=>{const f=fixture();f.pending();const job=await f.sync.start(lead,entry);await f.sync.step(lead,entry,job.jobId);const upload=await f.sync.step(lead,entry,job.jobId);assert.equal(upload.completed,0);assert.equal((await f.sync.start(lead,entry)).jobId,job.jobId);await f.sync.step(lead,entry,job.jobId);const done=await f.sync.step(lead,entry,job.jobId);assert.equal(done.status,'Synced');});
test('paused, archived, unapproved and changed-folder departments are excluded from answers',async()=>{const f=fixture();await finish(f);for(const changes of [{enabled:false},{archived:true},{approved:false},{driveFolderId:'new-folder'}])assert.equal((await f.sync.active([{...entry,...changes}])).length,0);});
test('empty folder sync withdraws every previous source',async()=>{const f=fixture();await finish(f);f.setFiles([]);const result=await finish(f);assert.equal(result.status,'Synced');assert.equal(result.sourceCount,0);assert.equal((await f.sync.active([entry])).length,0);});
test('concurrent sync steps cannot both upload the same file',async()=>{const f=fixture(),job=await f.sync.start(lead,entry);const results=await Promise.allSettled([f.sync.step(lead,entry,job.jobId),f.sync.step(lead,entry,job.jobId)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);});
test('source limits and unsafe folder links fail before import',()=>{assert.throws(()=>validateSourceFiles([{...file,mimeType:'application/vnd.google-apps.shortcut'}]),/UNSUPPORTED_SOURCE/);assert.throws(()=>validateSourceFiles([{...file,size:9*1024*1024}]),/SOURCE_TOO_LARGE/);assert.throws(()=>validateSourceFiles([{...file,capabilities:{canDownload:false}}]),/SOURCE_DOWNLOAD_DENIED/);assert.equal(validateNotebook({department:'LS CCA',title:'CCA',driveFolderId:'https://drive.google.com/drive/folders/one',ownerEmail:lead.email,approved:true,enabled:true}).driveFolderId,'one');assert.throws(()=>validateNotebook({department:'CCA',title:'CCA',driveFolderId:'https://drive.google.com.evil.test/drive/folders/one'}));});
test('answers require cited evidence mapped to the active source manifest',()=>{const active=[{...entry,store:'fileSearchStores/store',files:[file],syncedAt:'today'}];const reply={candidates:[{finishReason:'STOP',content:{parts:[{text:'Use the guidance.'}]},groundingMetadata:{groundingChunks:[{retrievedContext:{title:'drive:'+file.id+':'+file.name,fileSearchStore:'fileSearchStores/store'}}],groundingSupports:[{groundingChunkIndices:[0]}]}}]};assert.equal(groundedDriveAnswer(reply,active).citations[0].sourceId,file.id);assert.equal(groundedDriveAnswer(reply,[]),null);reply.candidates[0].groundingMetadata.groundingSupports=[];assert.equal(groundedDriveAnswer(reply,active),null);});
test('Drive service stays disabled without explicit provider and credentials',()=>{assert.equal(driveSearchReady({GEMINI_API_KEY:'old-key'}),false);assert.equal(driveSearchReady({ANSWER_PROVIDER:'drive-file-search',GEMINI_API_KEY:'key',GEMINI_MODEL:'gemini-approved',DRIVE_SERVICE_ACCOUNT_EMAIL:'service@school.test',DRIVE_SERVICE_ACCOUNT_PRIVATE_KEY:'configured'}),true);});
test('HTTP sync denies another department and exposes no private catalog to ordinary staff',async()=>{const env={ANSWER_PROVIDER:'drive-file-search',GEMINI_API_KEY:'key',GEMINI_MODEL:'gemini-approved',DRIVE_SERVICE_ACCOUNT_EMAIL:'service@school.test',DRIVE_SERVICE_ACCOUNT_PRIVATE_KEY:'configured',GOOGLE_CLIENT_ID:'client',GOOGLE_ALLOWED_DOMAIN:'school.test',STAFF_EMAILS:other.email};const h=createHandler(env,()=>{throw Error('No upstream request allowed');},async()=>other,{read:async()=>({entries:[entry]})},{active:async()=>[]});const request=new Request('https://ask.test/.netlify/functions/ask?route=sync',{method:'POST',body:JSON.stringify({action:'start',id:entry.id})});assert.equal((await h(request)).status,403);assert.equal((await h(new Request('https://ask.test/.netlify/functions/ask?route=notebooks'))).status,403);});
test('live chat route selects server stores and returns a mapped Drive citation',async()=>{const env={ANSWER_PROVIDER:'drive-file-search',GEMINI_API_KEY:'key',GEMINI_MODEL:'gemini-approved',DRIVE_SERVICE_ACCOUNT_EMAIL:'service@school.test',DRIVE_SERVICE_ACCOUNT_PRIVATE_KEY:'configured',GOOGLE_CLIENT_ID:'client',GOOGLE_ALLOWED_DOMAIN:'school.test',STAFF_EMAILS:lead.email};const active=[{...entry,store:'fileSearchStores/cca',files:[file],syncedAt:'2026-10-05'}];let sent;const h=createHandler(env,async(url,options)=>{sent=JSON.parse(options.body);return Response.json({candidates:[{finishReason:'STOP',content:{parts:[{text:'Use the muster guidance.'}]},groundingMetadata:{groundingChunks:[{retrievedContext:{title:'drive:'+file.id+':'+file.name}}],groundingSupports:[{groundingChunkIndices:[0]}]}}]});},async()=>lead,{read:async()=>({entries:[entry]})},{active:async()=>active});const res=await h(new Request('https://ask.test/.netlify/functions/ask?route=chat',{method:'POST',body:JSON.stringify({message:'Where?',stores:['evil'],language:'en'})}));assert.equal(res.status,200);assert.equal((await res.json()).citations[0].sourceId,file.id);assert.deepEqual(sent.tools[0].fileSearch.fileSearchStoreNames,['fileSearchStores/cca']);});
test('chat withholds an answer when its department is paused during retrieval',async()=>{const env={ANSWER_PROVIDER:'drive-file-search',GEMINI_API_KEY:'key',GEMINI_MODEL:'gemini-approved',DRIVE_SERVICE_ACCOUNT_EMAIL:'service@school.test',DRIVE_SERVICE_ACCOUNT_PRIVATE_KEY:'configured',GOOGLE_CLIENT_ID:'client',GOOGLE_ALLOWED_DOMAIN:'school.test',STAFF_EMAILS:lead.email};let reads=0;const h=createHandler(env,async()=>Response.json({candidates:[]}),async()=>lead,{read:async()=>({entries:[entry]})},{active:async()=>++reads===1?[{store:'fileSearchStores/cca',files:[file]}]:[]});const res=await h(new Request('https://ask.test/.netlify/functions/ask?route=chat',{method:'POST',body:JSON.stringify({message:'Where?'})}));assert.equal(res.status,409);assert.equal((await res.json()).error,'SOURCES_UPDATED');});
